"""add enable_face_recognition to alert_rules

Revision ID: cfc80f71c49f
Revises: 88dd8b98d05b
Create Date: 2026-04-28 03:52:52.027439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc80f71c49f'
down_revision: Union[str, None] = '88dd8b98d05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('enable_face_recognition', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'enable_face_recognition')
    # ### end Alembic commands ###
